import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UIProvider, CartProvider } from "../providers";
import { CartPanel } from "@/components/CartPanel/CartPanel.server";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Develop (store)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white`}
      >
        <UIProvider>
          <CartProvider>
            <main className="min-h-screen">{children}</main>
            <CartPanel />
          </CartProvider>
        </UIProvider>
      </body>
    </html>
  );
}
