"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navbar/Navbar_";
import { AuthProvider, UIProvider, CartProvider } from "../providers";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Develop (store)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${inter.className} bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white`}
        >
          <UIProvider>
            <CartProvider>
              <NavBar />
              {children}
            </CartProvider>
          </UIProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
