import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UIProvider, CartProvider } from "../providers";
import { CartPanel } from "@/components/CartPanel/CartPanel.server";
import Navbar from "@/components/Navbar/Navbar.server";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Develop (store)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <CartProvider>
          <UIProvider>
            <main className="dark text-foreground bg-background min-h-screen">
              <Navbar />
              {children}
              <CartPanel />
            </main>
          </UIProvider>
        </CartProvider>
      </body>
    </html>
  );
}
